# here are some handy aliases

FUNCPATH=~/
source $FUNCPATH

CUR_DIR="$PWD"
ALIASESPATH="${CUR_DIR}/${BASH_ARGV[0]}"
FUNCPATH="${CUR_DIR}/git_functions.sh"

alias ?="source $ALIASESPATH"
alias ??="nano $ALIASESPATH && source $ALIASESPATH" # edit this file, and then evaluate its content


# ~/.wtf && wtf" # edit that printout

# this is the hdmi/video one, it starts at boot
alias vnc-stop="pkill x11vnc"
alias vnc-start="/home/pi/.bootstart_vnc.sh &"

# alias vnc-start="x11vnc -display :0 -noxdamage -ncache 10 -ncache_cr &"
## x11vnc -forever -display :0 -noxdamage -ncache 10 -ncache_cr

# these is another desktop then the one coming out of hdmi/video output
alias vnc+-start="vncserver :1 -geometry 1024x768 -depth 24"
alias vnc+-stop="pkill Xtightvnc"

alias mosquitto_start="sudo /etc/init.d/mosquitto start"

## this is what you see (when type '?')
# echo "getip - get ip address"
echo "vnc-stop  - stop vnc server (it is running from boot)"
echo "vnc-start - start vnc server (same display as hdmi/vi ports)"
echo "node-red-stop - stop node-red server (it starts at boot)"
echo "node-red-start - start node-red server"
echo "mosquitto_start"  # start mosquitto

echo "nodered: http://"`hostname`".local:1881"

tiffi | lolcat -a
echo "?/??/rc"
echo ":))"

